# Generated by Django 5.0 on 2024-10-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the ingredient', max_length=100)),
                ('protein', models.FloatField(default=0, help_text='Amount of protein (in grams) per 100g of the ingredient')),
                ('fiber', models.FloatField(default=0, help_text='Amount of fiber (in grams) per 100g of the ingredient')),
                ('carbohydrate', models.FloatField(default=0, help_text='Amount of carbohydrates (in grams) per 100g of the ingredient')),
                ('calories', models.FloatField(default=0, help_text='Amount of salt (in grams) per 100g of the ingredient')),
                ('saturated_fatty_acid', models.FloatField(default=0, help_text='Amount of carbohydrates (in grams) per 100g of the ingredient')),
                ('allergens', models.CharField(choices=[('gluten', 'Gluten'), ('lactose', 'Lactose'), ('nuts', 'Nuts'), ('soy', 'Soy'), ('egg', 'Egg'), ('shellfish', 'Shellfish'), ('fish', 'Fish'), ('peanuts', 'Peanuts'), ('sesame', 'Sesame'), ('none', 'None')], default='none', help_text='Allergens associated with the ingredient', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Quantity of this ingredient in grams for the recipe')),
                ('ingredient', models.ForeignKey(help_text='The ingredient used in the recipe', on_delete=django.db.models.deletion.CASCADE, to='models.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the recipe', max_length=200)),
                ('image', models.URLField(help_text='The URL of the recipe image')),
                ('instructions', models.TextField(help_text='Instructions for preparing the recipe')),
                ('ingredients', models.ManyToManyField(help_text='The ingredients used in the recipe', through='models.IngredientQuantity', to='models.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='recipe',
            field=models.ForeignKey(help_text='The recipe this ingredient belongs to', on_delete=django.db.models.deletion.CASCADE, to='models.recipe'),
        ),
    ]
