# Generated by Django 5.0 on 2024-10-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Allergen associated with the ingredient', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='allergens',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(default=0, help_text='Amount of calories (in kcal) per 100g of the ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='The name of the ingredient', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='saturated_fatty_acid',
            field=models.FloatField(default=0, help_text='Amount of saturated fatty acids (in grams) per 100g of the ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, help_text='The URL of the recipe image', null=True),
        ),
        migrations.AddConstraint(
            model_name='ingredientquantity',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='ingredientquantity',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_recipe_name'),
        ),
        migrations.AddField(
            model_name='ingredientallergen',
            name='allergen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.allergen'),
        ),
        migrations.AddField(
            model_name='ingredientallergen',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.ingredient'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('protein__gte', 0), ('fiber__gte', 0), ('carbohydrate__gte', 0), ('calories__gte', 0)), name='positive_nutritional_values'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='allergens',
            field=models.ManyToManyField(blank=True, help_text='Allergens associated with the ingredient', through='models.IngredientAllergen', to='models.allergen'),
        ),
    ]
