# Generated by Django 5.0 on 2024-10-12 22:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_allergen_ingredientallergen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('snack', 'Snack'), ('meal', 'Meal')], default='meal', help_text='The type of the recipe (snack or meal)', max_length=5),
        ),
        migrations.CreateModel(
            name='RecipeVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedded_recipe', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Array of vector embeddings of the recipes', size=1024)),
                ('recipe', models.OneToOneField(help_text='Reference to the associated recipe', on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='models.recipe')),
            ],
        ),
    ]
